version: '3'
services:
  redis-master:
    container_name: "redis-master"
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-master:/data

  redis-slave1:
    container_name: "redis-slave1"
    image: redis
    ports:
      - "6380:6379"
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master
    volumes:
      - redis-slave1:/data

  redis-slave2:
    container_name: "redis-slave2"
    image: redis
    ports:
      - "6381:6379"
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master
    volumes:
      - redis-slave2:/data

  redis-sentinel1:
    container_name: 'redis-sentinel1'
    image: redis
    ports:
      - "26379:26379"
    command: >
      sh -c 'echo "bind 0.0.0.0" > /etc/sentinel.conf &&
      echo "sentinel monitor mymaster redis-master 6379 2" >> /etc/sentinel.conf &&
      echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
      echo "sentinel down-after-milliseconds mymaster 10000" >> /etc/sentinel.conf &&
      echo "sentinel failover-timeout mymaster 10000" >> /etc/sentinel.conf &&
      echo "sentinel parallel-syncs mymaster 1" >> /etc/sentinel.conf &&
      redis-sentinel /etc/sentinel.conf'
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

  redis-sentinel2:
    container_name: 'redis-sentinel2'
    image: redis
    ports:
      - "26380:26379"
    command: >
      sh -c 'echo "bind 0.0.0.0" > /etc/sentinel.conf &&
      echo "sentinel monitor mymaster redis-master 6379 2" >> /etc/sentinel.conf &&
      echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
      echo "sentinel down-after-milliseconds mymaster 10000" >> /etc/sentinel.conf &&
      echo "sentinel failover-timeout mymaster 10000" >> /etc/sentinel.conf &&
      echo "sentinel parallel-syncs mymaster 1" >> /etc/sentinel.conf &&
      redis-sentinel /etc/sentinel.conf'
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

  redis-sentinel3:
    container_name: 'redis-sentinel3'
    image: redis
    ports:
      - "26381:26379"
    command: >
      sh -c 'echo "bind 0.0.0.0" > /etc/sentinel.conf &&
      echo "sentinel monitor mymaster redis-master 6379 2" >> /etc/sentinel.conf &&
      echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
      echo "sentinel down-after-milliseconds mymaster 10000" >> /etc/sentinel.conf &&
      echo "sentinel failover-timeout mymaster 10000" >> /etc/sentinel.conf &&
      echo "sentinel parallel-syncs mymaster 1" >> /etc/sentinel.conf &&
      redis-sentinel /etc/sentinel.conf'
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

volumes:
  redis-master:
    driver: local
  redis-slave1:
    driver: local
  redis-slave2:
    driver: local
