version: '3'

services:
  redis-configurer:
    container_name: "redis-configurer"
    image: redis:6.0-alpine
    command: >
      sh -c 'echo yes | redis-cli -h 172.22.0.2 -p 6379 --cluster create \
        172.22.0.2:6379 172.22.0.3:6379 172.22.0.4:6379 \
        172.22.0.5:6379 172.22.0.6:6379 172.22.0.7:6379 \
        --cluster-replicas 1 && tail -f /dev/null'
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
    networks:
      redis-net:
        ipv4_address: 172.22.0.10

  redis-1:
    container_name: "redis-1"
    image: redis:6.0-alpine
    ports:
      - 7001:6379
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    depends_on:
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
    networks:
      redis-net:
        ipv4_address: 172.22.0.2

  redis-2:
    container_name: "redis-2"
    image: redis:6.0-alpine
    ports:
      - 7002:6379
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    networks:
      redis-net:
        ipv4_address: 172.22.0.3

  redis-3:
    container_name: "redis-3"
    image: redis:6.0-alpine
    ports:
      - 7003:6379
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    networks:
      redis-net:
        ipv4_address: 172.22.0.4

  redis-4:
    container_name: "redis-4"
    image: redis:6.0-alpine
    ports:
      - 7004:6379
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    networks:
      redis-net:
        ipv4_address: 172.22.0.5

  redis-5:
    container_name: "redis-5"
    image: redis:6.0-alpine
    ports:
      - 7005:6379
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    networks:
      redis-net:
        ipv4_address: 172.22.0.6

  redis-6:
    container_name: "redis-6"
    image: redis:6.0-alpine
    ports:
      - 7006:6379
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]

    networks:
      redis-net:
        ipv4_address: 172.22.0.7

networks:
  redis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16